### ISSUE TITLE
Dependency break with sqlalchemy==1.4 caused by snowflake-sqlalchemy

### ISSUE THREAD

**Issue by BrendanFrick** [fivetran/great_expectations#2552]
**Describe the bug**
`import great_expectations` fails when [`snowflake_sqlalchemy`](https://github.com/snowflakedb/snowflake-sqlalchemy) is also installed in the environment. This is because of a change introduced in `sqlalchemy==1.4.0`

**To Reproduce**
1. Create environment  
```
  python3 -m venv test-ge
  source test-ge/bin/activate
  pip install --upgrade pip==21.0.1
  pip install great-expectations==0.13.13
  pip install snowflake-sqlalchemy==1.2.4
```

2. Try importing great-expectations
```
python3 -c "import great_expectations" 
```

3.  Receive error
```
   ....
  File "~/envs/test-ge/lib/site-packages/great_expectations/dataset/sqlalchemy_dataset.py", line 75, in <module>
    registry.register("snowflake", "snowflake.sqlalchemy", "dialect")
AttributeError: 'NoneType' object has no attribute 'register'
````

**Expected behavior**
- Expect `import great_expectations` to compile cleanly with `snowflake-sqlalchemy` installed
 
**Environment (please complete the following information):**
 - Operating System: [Linux, Windows]
 - Great Expectations Version: [e.g. 0.13.13]

**Additional context**
- SQLAlchemy 1.4 was released on 03/15/2021
- `snowflake-sqlalchemy` pins `sqlalchemy <= 2.0.0`. Unclear if there are any dependency issues with current `snowflake-sqlalchemy` and `sqlalchemy 1.4`

**Comment by Shinnnyshinshin** [comment]
addressed by #2553

**Comment by lukedyer-peak** [comment]
@Shinnnyshinshin I'm getting this error also affecting great_expectations in general as not all the sqlalchemy imports work with >= `1.4.0` 
https://github.com/great-expectations/great_expectations/blob/18234477693306e5e3845e69a1be78a85c639295/great_expectations/dataset/sqlalchemy_dataset.py#L42

I think the version should also be pinned in the user installation

**Comment by lukedyer-peak** [comment]
This won't show up in the tests as the SA tests pin the version by that PR.

**Comment by Shinnnyshinshin** [comment]
@lukedyer-peak you're absolutely right. Thank you so much for catching this. I'll approve #2600 which you just submitted.

**Comment by Shinnnyshinshin** [comment]
Your change should be part of the upcoming GE 0.13.15 :)
