### ISSUE TITLE
Profiling BigQuery table issue whilst great_expectations init

### ISSUE THREAD

**Issue by Confman** [fivetran/great_expectations#1174]
Version: 0.9.3

BigQuery integration with `great_expectations init` results in getting the following error:

```Generating example Expectation Suite...
Traceback (most recent call last):
  File "/Users/hakan.gurel/Desktop/Develop/anaconda3/envs/ml/bin/great_expectations", line 8, in <module>
    sys.exit(main())
  File "/Users/hakan.gurel/Desktop/Develop/anaconda3/envs/ml/lib/python3.7/site-packages/great_expectations/cli/cli.py", line 58, in main
    cli()
  File "/Users/hakan.gurel/Desktop/Develop/anaconda3/envs/ml/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hakan.gurel/Desktop/Develop/anaconda3/envs/ml/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/hakan.gurel/Desktop/Develop/anaconda3/envs/ml/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hakan.gurel/Desktop/Develop/anaconda3/envs/ml/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hakan.gurel/Desktop/Develop/anaconda3/envs/ml/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/hakan.gurel/Desktop/Develop/anaconda3/envs/ml/lib/python3.7/site-packages/great_expectations/cli/init.py", line 123, in init
    open_docs=view,
  File "/Users/hakan.gurel/Desktop/Develop/anaconda3/envs/ml/lib/python3.7/site-packages/great_expectations/cli/datasource.py", line 906, in create_expectation_suite
    additional_batch_kwargs=additional_batch_kwargs
  File "/Users/hakan.gurel/Desktop/Develop/anaconda3/envs/ml/lib/python3.7/site-packages/great_expectations/data_context/data_context.py", line 1219, in profile_data_asset
    expectation_suite, validation_results = profiler.profile(batch, run_id=run_id)
  File "/Users/hakan.gurel/Desktop/Develop/anaconda3/envs/ml/lib/python3.7/site-packages/great_expectations/profile/base.py", line 62, in profile
    expectation_suite = cls._profile(data_asset)
  File "/Users/hakan.gurel/Desktop/Develop/anaconda3/envs/ml/lib/python3.7/site-packages/great_expectations/profile/sample_expectations_dataset_profiler.py", line 276, in _profile
    column = cls._find_next_string_column(dataset, columns, profiled_columns, column_cache)
  File "/Users/hakan.gurel/Desktop/Develop/anaconda3/envs/ml/lib/python3.7/site-packages/great_expectations/profile/sample_expectations_dataset_profiler.py", line 182, in _find_next_string_column
    type = cls._get_column_type_with_caching(dataset, column, column_cache)
  File "/Users/hakan.gurel/Desktop/Develop/anaconda3/envs/ml/lib/python3.7/site-packages/great_expectations/profile/sample_expectations_dataset_profiler.py", line 34, in _get_column_type_with_caching
    column_type = cls._get_column_type(dataset, column_name)
  File "/Users/hakan.gurel/Desktop/Develop/anaconda3/envs/ml/lib/python3.7/site-packages/great_expectations/profile/basic_dataset_profiler.py", line 42, in _get_column_type
    elif df.expect_column_values_to_be_in_type_list(column, type_list=sorted(list(cls.STRING_TYPE_NAMES))).success:
  File "/Users/hakan.gurel/Desktop/Develop/anaconda3/envs/ml/lib/python3.7/site-packages/great_expectations/data_asset/util.py", line 85, in f
    return self.mthd(obj, *args, **kwargs)
  File "/Users/hakan.gurel/Desktop/Develop/anaconda3/envs/ml/lib/python3.7/site-packages/great_expectations/data_asset/data_asset.py", line 238, in wrapper
    raise err
  File "/Users/hakan.gurel/Desktop/Develop/anaconda3/envs/ml/lib/python3.7/site-packages/great_expectations/data_asset/data_asset.py", line 225, in wrapper
    return_obj = func(self, **evaluation_args)
  File "/Users/hakan.gurel/Desktop/Develop/anaconda3/envs/ml/lib/python3.7/site-packages/great_expectations/dataset/sqlalchemy_dataset.py", line 786, in expect_column_values_to_be_in_type_list
    type_module.__name__)
AttributeError: 'BigQueryTypes' object has no attribute '__name__'
```

At this failed state, it also keeps the temporary table on BigQuery.

Getting the same error with various tables.

As far as I remember correctly, it used to be working on previous version (0.8).

**Comment by jcampbell** [comment]
Thank you very much for reporting this. I have identified the issue -- it is related to a workaround for a problem with the pybigquery driver...which has now been fixed.

I'm inclined to just go to the more direct approach of using the updated driver, but that would require ensuring everyone is on the latest pybigquery release. Would that be a problem for anyone following this issue?

**Comment by jcampbell** [comment]
Update on the above -- I built a PR to address the issue both for older and newer versions of the pybigquery driver.

**Comment by jcampbell** [comment]
Closing for now
