### ISSUE TITLE
batch_request passed in to SimpleCheckpoint errors

### ISSUE THREAD

**Issue by lyra-victor** [fivetran/great_expectations#2647]
**Describe the bug**
When creating a `SimpleCheckpoint` and passing in a `batch_request: BatchRequest`, it seems to treat the `batch_request` as a dictionary instead of a `BatchRequest` and errors out `AttributeError: 'BatchRequest' object has no attribute 'items'` [here](https://github.com/great-expectations/great_expectations/blob/0.13.17/great_expectations/core/util.py#L71)

**To Reproduce**
```python


import great_expectations as ge
from great_expectations.core.batch import RuntimeBatchRequest
from great_expectations.cli.datasource import sanitize_yaml_and_save_datasource
from great_expectations.checkpoint import SimpleCheckpoint

import pandas as pd


context = ge.get_context()
df = pd.DataFrame({"col1": ["a", "a", "b", "c"], "col2": [1, 2, 3, 4]})
config = """
    name: my_pandas_datasource
    class_name: Datasource
    execution_engine:
        class_name: PandasExecutionEngine
    data_connectors:
        my_runtime_data_connector:
          class_name: RuntimeDataConnector
          batch_identifiers:
              - some_batch_identifier_so_this_can_work
"""



context.test_yaml_config(
    yaml_config=config
)
sanitize_yaml_and_save_datasource(context, config, overwrite_existing=True)


runtime_batch_request = RuntimeBatchRequest(
    datasource_name="my_pandas_datasource",
    data_connector_name="my_runtime_data_connector",
    data_asset_name="insert_your_data_asset_name_here",
    runtime_parameters={
      "batch_data": df
    },
    batch_identifiers={
        "some_batch_identifier_so_this_can_work": "blah",
    }
)
my_checkpoint = SimpleCheckpoint(
    name="my_checkpoint",
    data_context=context,
    batch_request = runtime_batch_request
)

>>

AttributeError                            Traceback (most recent call last)
<ipython-input-1-b72466658554> in <module>
     43     name="my_checkpoint",
     44     data_context=context,
---> 45     batch_request = runtime_batch_request
     46 )

~/.pyenv/versions/anaconda3-2020.02/envs/sandbox/lib/python3.7/site-packages/great_expectations/checkpoint/checkpoint.py in __init__(self, name, data_context, config_version, template_name, module_name, class_name, run_name_template, expectation_suite_name, batch_request, action_list, evaluation_parameters, runtime_configuration, validations, profilers, validation_operator_name, batches, site_names, slack_webhook, notify_on, notify_with, **kwargs)
    672             slack_webhook=slack_webhook,
    673             notify_on=notify_on,
--> 674             notify_with=notify_with,
    675         ).build()
    676 

~/.pyenv/versions/anaconda3-2020.02/envs/sandbox/lib/python3.7/site-packages/great_expectations/checkpoint/configurator.py in build(self)
    112         self._validate_slack_configuration()
    113 
--> 114         return self._build_checkpoint_config()
    115 
    116     def _build_checkpoint_config(self) -> CheckpointConfig:

~/.pyenv/versions/anaconda3-2020.02/envs/sandbox/lib/python3.7/site-packages/great_expectations/checkpoint/configurator.py in _build_checkpoint_config(self)
    134                         "config_version": self.other_kwargs.pop("config_version", 1.0)
    135                         or 1.0,
--> 136                         **self.other_kwargs,
    137                     }
    138                 )

~/.pyenv/versions/anaconda3-2020.02/envs/sandbox/lib/python3.7/site-packages/great_expectations/data_context/types/base.py in update(self, other_config, runtime_kwargs)
   1743                 updated_batch_request = nested_update(
   1744                     batch_request,
-> 1745                     other_batch_request,
   1746                 )
   1747                 self._batch_request = updated_batch_request

~/.pyenv/versions/anaconda3-2020.02/envs/sandbox/lib/python3.7/site-packages/great_expectations/core/util.py in nested_update(d, u, dedup)
     69 ):
     70     """update d with items from u, recursively and joining elements"""
---> 71     for k, v in u.items():
     72         if isinstance(v, Mapping):
     73             d[k] = nested_update(d.get(k, {}), v, dedup=dedup)

AttributeError: 'RuntimeBatchRequest' object has no attribute 'items'
```
**Expected behavior**
I expected the above to work since I'm passing in `batch_request: BatchRequest`

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.13.17

**Additional context**
None

**Comment by eugmandel** [comment]
@lyra-victor Thank you for reporting. We will post here once we look at this issue deeper.

**Comment by geertjandev** [comment]
hitting the same issue / error, any update or workarounds for this?

**Comment by rr-chiranjeevi-ds** [comment]
I am facing same issue but for snowflake datasource. Is there any fix to this?

**Comment by cdkini** [comment]
Hey @lyra-victor @geertjan-garvis @rr-chiranjeevi-ds thanks so much for point this out!

I apologize for the delay; the core team has been focusing on a few other features so this fell into our backlog. @bhcastleton put this on my radar earlier today and I'll definitely be making it a priority moving forward. 

It looks like there's a mismatch of types when we get to the `nested_update` function so I'll have to do a bit of digging to see why that is. To be fully transparent, I am a bit new to this part of the codebase but I'll keep this thread updated with any findings.

Thanks again for your patience 🙏🏽

**Comment by cdkini** [comment]
I opened up PR https://github.com/great-expectations/great_expectations/pull/3152 to start making some fixes here.

Here's the output I'm seeing when I run your code:

```
Attempting to instantiate class from config...
	Instantiating as a Datasource, since class_name is Datasource
	Successfully instantiated Datasource


ExecutionEngine class name: PandasExecutionEngine
Data Connectors:
	my_runtime_data_connector : RuntimeDataConnector

	Available data_asset_names (0 of 0):

	Unmatched data_references (0 of 0): []
```

And here is what I see when I inspect `my_checkpoint` in my debugger:
![Screen Shot 2021-07-30 at 4 40 44 PM](https://user-images.githubusercontent.com/49923762/127709400-e2e22e1c-1fbd-4b85-90b8-ef33b29ef3c4.png)

I'm a bit perplexed as to why `nested_update` was able to work in situations where we had objects of different types. I want to look into this a bit more and also write a test or two to ensure coverage moving forward.

**Comment by cdkini** [comment]
A PR has been issued and is going through the review process. You can see the changes made at #3152 and make any comments/suggestions there if you wish!

We'll hopefully have this merged and ready to use shortly.

**Comment by cdkini** [comment]
The interaction between `SimpleCheckpoint` and `RuntimeDataConnectors` seemed to have some issues but I think we've now covered them. Changes have been approved and the PR should be merging shortly.

Please let me know if any other issues around this matter arise during your usage of GE!

**Comment by cdkini** [comment]
Reopening issue due to similar issue; open to investigate.

**Comment by rr-chiranjeevi-ds** [comment]
Hi @cdkini  I am facing the error after upgrading great expectations to v0.13.26 .
`Traceback (most recent call last):
  File "/Users/chiranjeevi.ds/ge/great_expectations/uncommitted/run_account_adjustments.py", line 73, in <module>
    result: CheckpointResult = data_context.run_checkpoint(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/great_expectations/data_context/data_context.py", line 3142, in run_checkpoint
    return checkpoint.run(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/great_expectations/checkpoint/checkpoint.py", line 251, in run
    substituted_runtime_config: CheckpointConfig = self.get_substituted_config(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/great_expectations/checkpoint/checkpoint.py", line 139, in get_substituted_config
    ] = runtime_kwargs_batch_request.to_json_dict()
AttributeError: 'RuntimeBatchRequest' object has no attribute 'to_json_dict'`

I have mentioned the config file below 
```
config_version: 3.0 
datasources:
  new_db:
    class_name: Datasource
    data_connectors:
      default_runtime_data_connector_name:
        batch_identifiers:
          - default_identifier_name
        class_name: RuntimeDataConnector
        module_name: great_expectations.datasource.data_connector
      default_inferred_data_connector_name:
        class_name: InferredAssetSqlDataConnector
        module_name: great_expectations.datasource.data_connector
      inferred_data_connector_name:
        class_name: InferredAssetSqlDataConnector
        datasource_name:
          base_directory: queries
          default_regex:
            group_names:
              - data_asset_name
            pattern: .sql
        module_name: great_expectations.datasource.data_connector
    module_name: great_expectations.datasource
    execution_engine:
      class_name: SqlAlchemyExecutionEngine
      credentials:
        host: host
        username: user
        database: my_db
        query:
          schema: test
          warehouse: test_wh
          role: test_role
        connect_args:
          authenticator: externalbrowser
        drivername: snowflake
      module_name: great_expectations.execution_engine
  custom_db:
      class_name: SqlAlchemyDatasource
      credentials: ${my_db}
      data_asset_type:
        class_name: SqlAlchemyDataset
        module_name: great_expectations.dataset
      batch_kwargs_generators:
        tables:
          class_name: TableBatchKwargsGenerator
        queries:
          class_name: QueryBatchKwargsGenerator
          query_store_backend:
            class_name: TupleFilesystemStoreBackend
            filepath_suffix: .sql
            base_directory: queries
  inferred_db:
      class_name: Datasource
      execution_engine:
        class_name: SqlAlchemyExecutionEngine
        credentials:
          host: host
          username: user
          database: my_db
          query:
            schema: test
            warehouse: test_wh
            role: test_role
          connect_args:
            authenticator: externalbrowser
          drivername: snowflake
          module_name: great_expectations.execution_engine
      data_connectors:
        default_inferred_data_connector_name:
          class_name: InferredAssetSqlDataConnector
          name: whole_table
        default_runtime_data_connector_name:
          class_name: RuntimeDataConnector
          batch_identifiers:
            - default_identifier_name
 


config_variables_file_path: uncommitted/config_variables.yml
 
plugins_directory: plugins/

stores: 
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  validations_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/

  evaluation_parameter_store: 
    class_name: EvaluationParameterStore

  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/

expectations_store_name: expectations_store
validations_store_name: validations_store
evaluation_parameter_store_name: evaluation_parameter_store
checkpoint_store_name: checkpoint_store

data_docs_sites:
  local_site:
    class_name: SiteBuilder
    # set to false to hide how-to buttons in Data Docs
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder

anonymous_usage_statistics:
  enabled: true
  data_context_id: 3bf16b44-e25e-4005-9088-0fc16afbd991
notebooks:
```

And i am trying to run the checkpoint passing batch request as below 
`batch_request = RuntimeBatchRequest(
    datasource_name="inferred_db",
    data_connector_name="default_runtime_data_connector_name",
    data_asset_name="custom_sql",  # this can be anything that identifies this data
    runtime_parameters={"query": "SELECT * from test1 LIMIT 10"},
    batch_identifiers={"default_identifier_name": "identifier"},
)`

Here is the checkpoint 

```
name: test
config_version: 1.0
template_name:
module_name: great_expectations.checkpoint
class_name: Checkpoint
run_name_template: '%Y%m%d-%H%M%S-my-run-name-template'
expectation_suite_name:
batch_request:
action_list:
  - name: store_validation_result
    action:
      class_name: StoreValidationResultAction
  - name: store_evaluation_params
    action:
      class_name: StoreEvaluationParametersAction
  - name: update_data_docs
    action:
      class_name: UpdateDataDocsAction
      site_names: []
evaluation_parameters: {}
runtime_configuration: {}
validations:
  - batch_request:
      datasource_name: new_db
      data_connector_name: inferred_data_connector_name
      data_asset_name: test
    expectation_suite_name: test_expectation
profilers: []
ge_cloud_id:
```
Here is the python script 

```
import sys

from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
from great_expectations.core.batch import BatchRequest, RuntimeBatchRequest
from great_expectations.data_context import DataContext

data_context: DataContext = DataContext(context_root_dir="/Users/chiranjeevi.ds/ge/great_expectations")

batch_request = RuntimeBatchRequest(
    datasource_name="inferred_db",
    data_connector_name="default_runtime_data_connector_name",
    data_asset_name="custom_sql",  # this can be anything that identifies this data
    runtime_parameters={"query": "SELECT * from test1 LIMIT 10"},
    batch_identifiers={"default_identifier_name": "identifier"},
)
result: CheckpointResult = data_context.run_checkpoint(
    checkpoint_name="test_checkpoint",
    batch_request=batch_request,
    run_name=None,
)

if not result["success"]:
    print("Validation failed!")
    sys.exit(1)

print("Validation succeeded!")
sys.exit(0)

```

**Comment by cdkini** [comment]
I believe the issue was caused by a simple typo in the method invocation (`to_json_dict` is actually `get_json_dict` in the `BatchRequest` class)

**Comment by herrykarmito92** [comment]
@cdkini I'm very new on great expectations, I want to work with custom query using `BigQuery`

I tried to following this code , base on this url : [How to load a database table, view, or query result as a batch](https://github.com/great-expectations/great_expectations/blob/0.13.22/docs_rtd/guides/how_to_guides/creating_batches/how_to_load_a_database_table_view_or_query_result_as_a_batch.rst)

I facing this error : 
```
Loaded ExpectationSuite "bigquery.data_quality.store_info_missing" containing 0 expectations.
Traceback (most recent call last):
  File "/Users/herry/Project/python-flash-coffee/airflow/dags/include/great_expectations/uncommitted/test.py", line 20, in <module>
    my_validator: Validator = context.get_validator(
  File "/Users/herry/Project/python/airflow/env/lib/python3.9/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 932, in get_validator
    self.get_batch_list(
  File "/Users/herry/Project/python/airflow/env/lib/python3.9/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 294, in usage_statistics_wrapped_method
    result = func(*args, **kwargs)
  File "/Users/herry/Project/python/airflow/env/lib/python3.9/site-packages/great_expectations/data_context/data_context/base_data_context.py", line 1229, in get_batch_list
    return super().get_batch_list(
  File "/Users/herry/Project/python/airflow/env/lib/python3.9/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 1103, in get_batch_list
    return datasource.get_batch_list_from_batch_request(batch_request=batch_request)
  File "/Users/herry/Project/python/airflow/env/lib/python3.9/site-packages/great_expectations/datasource/new_datasource.py", line 160, in get_batch_list_from_batch_request
    raise ValueError(
ValueError: RuntimeBatchRequests must specify exactly one corresponding BatchDefinition
```

Here is the python script

```
import great_expectations as ge
from great_expectations import DataContext
from great_expectations.core import ExpectationSuite
from great_expectations.core.batch import RuntimeBatchRequest
from great_expectations.exceptions import DataContextError
from great_expectations.validator.validator import Validator

context: DataContext = ge.get_context()  

expectation_suite_name = "bigquery.data_quality.store_info_missing"

try:
    suite = context.get_expectation_suite(expectation_suite_name=expectation_suite_name)
    print(f'Loaded ExpectationSuite "{suite.expectation_suite_name}" containing {len(suite.expectations)} expectations.')
except DataContextError:
    suite = context.create_expectation_suite(expectation_suite_name=expectation_suite_name)
    print(f'Created ExpectationSuite "{suite.expectation_suite_name}".')


my_validator: Validator = context.get_validator(
    datasource_name = "production",
    data_connector_name = "default_inferred_data_connector_name",
    data_asset_name = "test1.store", # this can be anything that identifies this data_asset for you
    runtime_parameters={
        "query": "SELECT * FROM test1.store LIMIT 10"
    },
    batch_identifiers={
        "some_key_maybe_pipeline_stage": "validation_stage",
        "some_other_key_maybe_run_id": 1234567890
    },
    # Use batch_spec_passthrough to control whether the associated SqlAlchemy Execution Engine will create
    # a temporary table
    batch_spec_passthrough={
      "create_temp_table": False  # if not provided, this defaults to True
    },
    expectation_suite = suite,
)

my_validator.active_batch.head()

```
I cannot find out on stackoverflow of github issue about this issue
any help from your side ?

Thanks

**Comment by kirilscherbach** [comment]
I have the same issue as herrykarmito92

**Comment by munivinayk** [comment]
I have the same issue as herrykarmito92 and kirilscherbach

**Comment by karthigai-selvan** [comment]
I am also having the same issue as mentioned by herrykarmito92

**Comment by JustinGuese** [comment]
issue appeared again v0.15

**Comment by gburnside2** [comment]
I am having a similar issue on v0.18, is there a fix for this?
