### ISSUE TITLE
GE imports break with Altair 4.2.1 and jsonschema 3.2.0

### ISSUE THREAD

**Issue by epilif1017a** [fivetran/great_expectations#6957]
After Altair has released version 4.2.1, it no longer works with jsonschema 3.2.0, therefore the way the requirements are defined in GE python package are no longer 100% correct, because in certain scenarios, in the way the GE dependency versions are declared you can end up in an environment where you have altair 4.2.1 and jsonschema 3.2.0. 

```
python/lib/python3.8/site-packages/altair/utils/schemapi.py in validate_jsonschema(spec, schema, resolver)
     52     # it is not a valid URI reference due to the characters such as '<'.
     53     validator = JSONSCHEMA_VALIDATOR(
---> 54         schema, format_checker=JSONSCHEMA_VALIDATOR.FORMAT_CHECKER, resolver=resolver
     55     )
     56     error = jsonschema.exceptions.best_match(validator.iter_errors(spec))

AttributeError: type object 'Draft7Validator' has no attribute 'FORMAT_CHECKER'
```

**To Reproduce**
Just try to run import Great Expectations

**Expected behavior**
No issues when we try to import Great Expectations. And That dependencies are defined in a more conservative way so that we know they work along each other.

**Environment (please complete the following information):**
 - Linux
 - Great Expectations Version: 0.15.42

**Additional context**
Running on Spark 3.2.0
