### ISSUE TITLE
copy.deepcopy does not work on a ge_df when constructing ge_df with an expectations config

### ISSUE THREAD

**Issue by schrockn** [fivetran/great_expectations#342]
Repro:

```
import copy
import pandas as pd
import great_expectations as ge
df = pd.DataFrame.from_dict({'num1': [1, 3], 'num2': [2, 4]})
ge_df = ge.from_pandas(df, {'expectations':[]})
copy.deepcopy(ge_df)
```

Stack trace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/Users/schrockn/code/venvs/dagster/lib/python3.6/site-packages/pandas/core/generic.py", line 5119, in __deepcopy__
    return self.copy(deep=True)
  File "/Users/schrockn/code/venvs/dagster/lib/python3.6/site-packages/pandas/core/generic.py", line 5111, in copy
    return self._constructor(data).__finalize__(self)
  File "/Users/schrockn/code/venvs/dagster/lib/python3.6/site-packages/great_expectations/dataset/pandas_dataset.py", line 264, in __finalize__
    self.discard_subset_failing_expectations = other.discard_subset_failing_expectations
  File "/Users/schrockn/code/venvs/dagster/lib/python3.6/site-packages/pandas/core/generic.py", line 4372, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'PandasDataset' object has no attribute 'discard_subset_failing_expectations'

```

**Comment by jpcampb2** [comment]
It looks like what happened is that the value of `other` in `__finalize__` may have been coerced to be a `PandasDataset` by `_constructor` even when it was not `__init__`-ed as one (for example in the case of `DataFrame.copy()`.

Just created a PR to fix this... #344

**Comment by li-dennis** [comment]
I seem to be running into a similar issue after upgrading from pandas 0.25.3 to 1.3.2, but when it tries to look up `other._expectation_suite`. Maybe it's because i created a custom class that returns itself as the constructor?

https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/dataset/pandas_dataset.py#L415-L416

```
class DemandDF(PandasDataset):
    def _constructor(self) -> Type[DemandDF]:
        return DemandDF
```


```
AttributeError: 'DemandDF' object has no attribute '_expectation_suite'
  File "projects/tasks.py", line 694, in async_transform
    etl_state = deepcopy(
  File "copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "copy.py", line 205, in _deepcopy_list
    append(deepcopy(a, memo))
  File "copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "copy.py", line 153, in deepcopy
    y = copier(memo)
  File "pandas/core/generic.py", line 5949, in __deepcopy__
    return self.copy(deep=True)
  File "pandas/core/generic.py", line 5935, in copy
    return self._constructor(data).__finalize__(self, method="copy")
  File "great_expectations/dataset/pandas_dataset.py", line 402, in __finalize__
    self._initialize_expectations(other._expectation_suite)
  File "pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
```
