### ISSUE TITLE
SQLAlchemy==1.3.24 | Multi-column expectations not working

### ISSUE THREAD

**Issue by BilalZahid22** [fivetran/great_expectations#3468]
**Describe the bug**
With sqlalchemy==1.3.24 , multi-column expectations i.e.(expect_column_pair_values_A_to_be_greater_than_B) are throwing exceptions. But they are working on latest version of sqlalchemy i.e.(sqlalchemy==1.4.25). 
The error is as follows: 
`File "...venv\lib\site-packages\great_expectations\expectations\metrics\map_metric_provider.py", line 2123, in _sqlalchemy_column_pair_map_condition_filtered_row_count
    return execution_engine.engine.execute(
AttributeError: 'ResultProxy' object has no attribute 'one'`

**To Reproduce**
1. Create expectation expect_column_pair_values_A_to_be_greater_than_B for snowflake using sqlalchemy==1.3.24.
2. Exception will occur on creation time of expectation or if its already created then on time of validation.

**Expected behavior**
There should be support for multi-column expectations on sqlalchemy==1.3.24 (As this is the highest version airflow currently supports)

**Environment (please complete the following information):**
 - Operating System: [Windows, WSL(Ubuntu)]
 - Great Expectations Version: [0.13.35]

**Additional context**
Airflow does not support sqlalchemy>1.3.24 right now. With versions greater than this, it's web server doesn't work. It's a known issue by airflow. So for using great expectations with airflow for snowflake , the version of sqlalchemy should not be greater than 1.3.24

**Comment by talagluck** [comment]
Thanks for raising this issue @BilalZahid22 ! We will review and be in touch soon.

**Comment by NathanFarmer** [comment]
Hi @BilalZahid22! This issue has been addressed by PR #3499 and the bug fix will be available in GE version 0.13.37.

**Comment by BilalZahid22** [comment]
This issue doesn't seem to be solved in great-expectations>=0.13.37. The problem still persists but with different error. For Example: Multicolumn Expectations are working on sqlalchemy==1.4.25 but they are still throwing exceptions on sqlalchemy==1.3.24. Now the exception trace is a following 

> expect_column_pair_values_to_be_equal raised an exception:
> columns argument to select() must be a Python list or other iterable
> Show exception traceback...
> 
> Traceback (most recent call last):
> File "D:\Work\Repo\venv\lib\site-packages\sqlalchemy\sql\selectable.py", line 3105, in __init__
> cols_present = bool(columns)
> File "D:\Work\Repo\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 535, in __bool__
> raise TypeError("Boolean value of this clause is not defined")
> TypeError: Boolean value of this clause is not defined
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
> File "D:\Work\Repo\venv\lib\site-packages\great_expectations\execution_engine\execution_engine.py", line 294, in resolve_metrics
> resolved_metrics[metric_to_resolve.id] = metric_fn(
> File "D:\Work\Repo\venv\lib\site-packages\great_expectations\expectations\metrics\map_metric_provider.py", line 2084, in _sqlalchemy_column_pair_map_condition_values
> query = sa.select(
> File "", line 2, in select
> File "", line 2, in __init__
> File "D:\Work\Repo\venv\lib\site-packages\sqlalchemy\util\deprecations.py", line 139, in warned
> return fn(*args, **kwargs)
> File "D:\Work\Repo\venv\lib\site-packages\sqlalchemy\sql\selectable.py", line 3107, in __init__
> util.raise_(
> File "D:\Work\Repo\venv\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
> raise exception
> sqlalchemy.exc.ArgumentError: columns argument to select() must be a Python list or other iterable
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "D:\Work\Repo\venv\lib\site-packages\great_expectations\validator\validator.py", line 670, in resolve_validation_graph
> self._resolve_metrics(
> File "D:\Work\Repo\venv\lib\site-packages\great_expectations\validator\validator.py", line 759, in _resolve_metrics
> return execution_engine.resolve_metrics(
> File "D:\Work\Repo\venv\lib\site-packages\great_expectations\execution_engine\execution_engine.py", line 298, in resolve_metrics
> raise ge_exceptions.MetricResolutionError(
> great_expectations.exceptions.exceptions.MetricResolutionError: columns argument to select() must be a Python list or other iterable

So it seems the error type is different but the problem still persists of backward compatibility with sqlalchemy.
