### PR TITLE
[BUGFIX] Restore SQLAlchemy 1.4 compatibility in column_values_unique (fixes #11875)

### LINKED ISSUE #11875: [BUGFIX] 1.17 breaks SQLAlchemy 1.4 compatibility: AttributeError: module 'sqlalchemy' has no attribute 'Select'
**Describe the bug**

great-expectations 1.17.0 introduced a reference to `sa.Select` (the SQLAlchemy 2.0-only top-level attribute) in `great_expectations/expectations/metrics/column_map_metrics/column_values_unique.py` via [#11828](https://github.com/great-expectations/great_expectations/pull/11828) ("Fix SingleStoreDB expectations").

In SQLAlchemy 1.4, `Select` is not exposed as a top-level attribute on the `sqlalchemy` module — it lives at `sqlalchemy.sql.expression.Select` (or `sqlalchemy.sql.Select`). Any user still on SQLAlchemy 1.4 hits the following at evaluation time of `expect_column_values_to_be_unique` (or any expectation that resolves the `column_values.unique.condition` metric):

```
AttributeError: module 'sqlalchemy' has no attribute 'Select'. Did you mean: 'select'?
```

This appears to be an unintentional regression — SQLAlchemy 1.4 is still officially supported per `reqs/requirements-dev-sqlalchemy1.txt` (`sqlalchemy<2.0.0`, comment: *"Used to construct the extras_requires dict in setup.py for sqlalchemy dialects that are not yet compatible with sqlalchemy 2.x"*) and `setup.py`'s `sqla1x_only_keys` (clickhouse, redshift, teradata).

**To Reproduce**

```python
# Python 3.12, SQLAlchemy 1.4.x, great-expectations 1.17.0+
import great_expectations as gx
context = gx.get_context()
# ... configure any SQL-backed datasource (Snowflake, Postgres, MySQL, etc.)
# Run a suite containing expect_column_values_to_be_unique
# Result: MetricResolutionError wrapping AttributeError on sa.Select
```

Full traceback excerpt:

```
File ".../great_expectations/expectations/metrics/column_map_metrics/column_values_unique.py", line 89, in _sqlalchemy_window
    from_clause = _table.subquery() if isinstance(_table, sa.Select) else _table
                                                          ^^^^^^^^^
AttributeError: module 'sqlalchemy' has no attribute 'Select'. Did you mean: 'select'?

The above exception was the direct cause of the following exception:

great_expectations.exceptions.exceptions.MetricResolutionError: module 'sqlalchemy' has no attribute 'Select'
```

**Expected behavior**

`expect_column_values_to_be_unique` (and other expectations using `column_values.unique.condition`) should continue to work on SQLAlchemy 1.4, which is still officially supported.

**Environment**

 - Operating System: Linux (containerized Airflow worker)
 - Great Expectations Version: 1.17.0 and 1.17.1 (introduced in 1.17.0)
 - SQLAlchemy Version: 1.4.54
 - Data Source: Snowflake (via snowflake-sqlalchemy 1.9.0)
 - Cloud environment: Airflow on Kubernetes

**Additional context**

The compatibility module `great_expectations.compatibility.sqlalchemy` already exposes a version-safe `Select`, imported from `sqlalchemy.sql.expression`:

```python
try:
    from sqlalchemy.sql.expression import Select
except (ImportError, AttributeError):
    Select = SQLALCHEMY_NOT_IMPORTED
```

The fix is to import `Select` from there in `column_values_unique.py` and replace the two `sa.Select` references (lines 68 and 89). This matches the project's existing compatibility convention (`"Please do not import sqlalchemy directly, import from great_expectations.compatibility.sqlalchemy instead."` per `pyproject.toml`).

Happy to submit a PR.

Last unaffected release: **1.16.1**.

### PR DESCRIPTION
**Pull request by ranophoenix**
## Summary

Fixes #11875 — great-expectations 1.17.0 introduced `isinstance(_table, sa.Select)` in `column_values_unique.py` (PR #11828). `Select` is not a top-level attribute on the `sqlalchemy` module in 1.4 — it was promoted there only in 2.0. Users on SQLAlchemy 1.4 hit:

```
AttributeError: module 'sqlalchemy' has no attribute 'Select'. Did you mean: 'select'?
```

wrapped in a `MetricResolutionError` whenever an expectation resolves the `column_values.unique.condition` metric.

## Root cause

In SQLAlchemy 1.4 the `Select` type lives at `sqlalchemy.sql.expression.Select`, not `sqlalchemy.Select`. PR #11828 added two references to the 2.0-only top-level alias.

## Fix

`great_expectations.compatibility.sqlalchemy` already re-exports a version-safe `Select` from `sqlalchemy.sql.expression` (works in both 1.4 and 2.0). Import it from there and use it in place of `sa.Select` — matches the existing pattern enforced by the `pyproject.toml` lint rule (*"Please do not import sqlalchemy directly, import from great_expectations.compatibility.sqlalchemy instead."*).

```diff
 from great_expectations.compatibility.sqlalchemy import (
+    Select,
     sqlalchemy as sa,
 )
```

```diff
-if isinstance(_table, sa.Select):
+if isinstance(_table, Select):
```

```diff
-from_clause = _table.subquery() if isinstance(_table, sa.Select) else _table
+from_clause = _table.subquery() if isinstance(_table, Select) else _table
```

## Why this is the right scope

SQLAlchemy 1.4 is still officially supported per `reqs/requirements-dev-sqlalchemy1.txt` (`sqlalchemy<2.0.0`, *"for sqlalchemy dialects that are not yet compatible with sqlalchemy 2.x"*) and the `sqla1x_only_keys` branch in `setup.py` (clickhouse, redshift, teradata). The regression here looks unintentional, not a deliberate API drop.

## Checklist

- [x] Description of PR changes above includes a link to an existing GitHub issue (#11875)
- [x] PR title is prefixed with `[BUGFIX]`

### CODE REVIEW

**Review by dmpeters — APPROVED** [review]

**Comment by ranophoenix** [comment]
@cla-bot check

**Review by calixtofelipe — APPROVED** [review]

**Review by joshua-stauffer — APPROVED** [review]
thanks for the bugfix, @ranophoenix, this will ship in the next release
